name: 'Coverage'
on:
  pull_request:
    branches:
      - master

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '17'
          cache: yarn
      - uses: artiomtr/jest-coverage-report-action@v2.0-rc.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
