name: 'Publish development release from git commit SHA'

on:
  - workflow_dispatch

jobs:
  publish_dev_release:
    name: Publish development release from git commit SHA
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 17
          cache: yarn
          registry-url: 'https://registry.npmjs.org'
      - run: yarn set version berry
      - run: yarn install --immutable
      - name: Assigning new version
        run: yarn version prerelease --commit-hooks=false --git-tag-version=false --preid=dev-${GITHUB_SHA:0:6}
      - name: Publishing release
        run: yarn run publish:dev
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_PUBLISH_TOKEN }}
