name: 'Publish release-candidate from package.json version'

on:
  - workflow_dispatch

jobs:
  publish:
    name: Publish release-candidate from package.json version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 17
          cache: yarn
          registry-url: 'https://registry.npmjs.org'
      - run: yarn set version 2.4.3
      - run: yarn install --immutable
      - name: Publishing release
        run: yarn run publish:dist
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_PUBLISH_TOKEN }}
