name: Publish release

on:
  page_build:
  release:
    types:
      - published

jobs:
  publish_release:
    name: Publish release
    if: "!github.event.release.prerelease"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 17
          cache: 'yarn'
          registry-url: https://registry.npmjs.org/
      - run: yarn set version berry
      - run: yarn install --immutable
      - run: yarn run publish:latest
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPMJS_PUBLISH_TOKEN}}

  publish_prerelease:
    name: Publish pre-release
    if: "github.event.release.prerelease"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 17
          cache: 'yarn'
          registry-url: https://registry.npmjs.org/
      - run: yarn set version berry
      - run: yarn install --immutable
      - run: yarn run publish:dist
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPMJS_PUBLISH_TOKEN}}
